import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { exportSvg } from './svgExport'

const box=(value:string|null)=>{const [x,y,width,height]=(value??'0 0 0 0').split(' ').map(Number);return{x,y,width,height,toJSON:()=>({})} as DOMRect}
function scene(viewBox:string,badgeBox='900 80 100 50',stroke=20){document.body.innerHTML=`<svg id="network-canvas" viewBox="${viewBox}"><g data-layer="canvas-background"><rect x="-9999" y="-9999" width="19998" height="19998"/></g><g data-layer="segments" data-test-bbox="100 100 500 250"><path class="segment-main" stroke-width="${stroke}"/></g><g data-layer="stations" data-test-bbox="70 45 620 390"><g class="station-label-group"><text>Long label</text></g></g><g data-layer="line-badges" data-test-bbox="${badgeBox}"><rect/></g><g data-layer="map-elements" data-test-bbox="40 500 300 60"><text>Map text</text><rect data-editor="true" x="-5000" width="10000"/></g><g data-layer="waypoints" data-editor="true" data-test-bbox="-8000 -8000 16000 16000"/></svg>`;return document.querySelector('svg')! as SVGSVGElement}

describe('complete-map SVG export bounds',()=>{
  beforeEach(()=>{Object.defineProperty(SVGElement.prototype,'getBBox',{configurable:true,value:vi.fn(function(this:SVGElement){return box(this.getAttribute('data-test-bbox'))})})})
  afterEach(()=>{document.body.innerHTML='';delete (SVGElement.prototype as {getBBox?:unknown}).getBBox})
  it('is invariant to editor camera pan and zoom',()=>{const a=exportSvg(scene('0 0 200 120'),true),b=exportSvg(scene('700 400 80 60'),true),read=(text:string)=>new DOMParser().parseFromString(text,'image/svg+xml').documentElement.getAttribute('viewBox');expect(read(a)).toBe(read(b));expect(read(a)).toBe('-2 3 1044 599')})
  it('expands for a line badge far outside the route body',()=>{const near=new DOMParser().parseFromString(exportSvg(scene('0 0 100 100','650 80 40 40'),false),'image/svg+xml').documentElement.getAttribute('viewBox')!.split(' ').map(Number),far=new DOMParser().parseFromString(exportSvg(scene('0 0 100 100','1800 80 100 50'),false),'image/svg+xml').documentElement.getAttribute('viewBox')!.split(' ').map(Number);expect(far[2]).toBeGreaterThan(near[2]+1000)})
  it('adds allowance for thick locally overridden strokes and excludes editor helpers',()=>{const text=exportSvg(scene('0 0 10 10','650 80 40 40',60),true),doc=new DOMParser().parseFromString(text,'image/svg+xml'),view=doc.documentElement.getAttribute('viewBox')!.split(' ').map(Number);expect(view[0]).toBe(-22);expect(view[2]).toBe(774);expect(text).not.toContain('data-editor');expect(text).not.toContain('canvas-background');const background=doc.querySelector('.export-background')!;expect(background.getAttribute('x')).toBe(String(view[0]));expect(background.getAttribute('width')).toBe(String(view[2]))})
})
