import type { ActualRouteProject, LabelDirection, Selection, SegmentMode, StructureType } from '../data/model'
import { uid } from '../data/model'
import { markRelationDateOverride, markSegmentDateOverride, phaseForRelation, phaseForSegment, type OpeningPhasePath } from '../data/openingPhases'
import { OpeningPhaseEditor } from './OpeningPhaseEditor'
import { getWaypointStructureAfter, setWaypointStructureAfter, updateStructureNode } from '../data/structure'
import { effectiveLabelRotation, inferLabelDirection, labelOffsetFor, LABEL_DIRECTIONS } from '../data/style'

const round=(value:number)=>Math.round(value*100)/100
const inferDirectionFromVector=(x:number,y:number,fallback:LabelDirection):LabelDirection=>inferLabelDirection(x,y)==='custom'?fallback:inferLabelDirection(x,y) as LabelDirection

const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <label className="field"><span>{label}</span>{children}</label>

export function Inspector({ project, selection, onChange, onDelete, onPhasePreview, onStartPhaseDrawing }: { project: ActualRouteProject; selection: Selection; onChange: (next: ActualRouteProject) => void; onDelete: () => void; onPhasePreview: (path: OpeningPhasePath | null) => void; onStartPhaseDrawing: (phaseId: string, lineId: string, stationId: string | null) => void }) {
  const patch = (mutate: (next: ActualRouteProject) => void) => { const next = structuredClone(project); mutate(next); onChange(next) }
  let content: React.ReactNode = <div className="empty-inspector"><span>◎</span><p>选择站点、区间、控制点或线路，查看和修改属性。</p></div>

  if (selection?.type === 'station') {
    const station = project.stations.find((item) => item.id === selection.id)
    if (station) { const labelDirection=inferLabelDirection(station.labelOffsetX,station.labelOffsetY),labelDistance=Math.hypot(station.labelOffsetX,station.labelOffsetY),labelRotation=effectiveLabelRotation(station,project.settings); content = <>
      <h3>站点</h3>
      <Field label="名称"><input value={station.name} onChange={(e) => patch((n) => { n.stations.find((s) => s.id === station.id)!.name = e.target.value })} /></Field>
      <Field label="外文站名"><textarea rows={3} value={station.nameS ?? ''} onChange={(e) => patch((n) => { n.stations.find((s) => s.id === station.id)!.nameS = e.target.value || undefined })} /></Field>
      <div className="field-grid"><Field label="X"><input type="number" value={Math.round(station.x)} onChange={(e) => patch((n) => { n.stations.find((s) => s.id === station.id)!.x = Number(e.target.value) })} /></Field><Field label="Y"><input type="number" value={Math.round(station.y)} onChange={(e) => patch((n) => { n.stations.find((s) => s.id === station.id)!.y = Number(e.target.value) })} /></Field></div>
      <section className="station-label-layout" data-testid="station-label-layout"><span className="eyebrow">站名布局</span>
        <Field label="方向"><select aria-label="站名方向" value={labelDirection} onChange={e=>{if(e.target.value==='custom')return;const direction=e.target.value as LabelDirection;patch(n=>{const offset=labelOffsetFor(direction,labelDistance);const target=n.stations.find(s=>s.id===station.id)!;target.labelOffsetX=offset.x;target.labelOffsetY=offset.y})}}><option value="custom">自定义</option>{LABEL_DIRECTIONS.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></Field>
        <Field label="距离"><input aria-label="站名距离" type="number" min="0" step="0.1" value={round(labelDistance)} onChange={e=>{const distance=Math.max(0,Number(e.target.value)||0);patch(n=>{const target=n.stations.find(s=>s.id===station.id)!;const direction=labelDirection==='custom'?inferDirectionFromVector(target.labelOffsetX,target.labelOffsetY,project.settings.defaultLabelDirection):labelDirection;const offset=labelOffsetFor(direction,distance);target.labelOffsetX=offset.x;target.labelOffsetY=offset.y})}}/></Field>
        <Field label="旋转"><div className="rotation-control"><select aria-label="站名旋转预设" value={[0,45,-45,90,-90].includes(labelRotation)?labelRotation:'custom'} onChange={e=>{if(e.target.value==='custom')return;patch(n=>{n.stations.find(s=>s.id===station.id)!.labelRotation=Number(e.target.value)})}}><option value="0">0°</option><option value="45">45°</option><option value="-45">-45°</option><option value="90">90°</option><option value="-90">-90°</option><option value="custom">自定义</option></select><input aria-label="站名旋转角度" type="number" step="1" value={labelRotation} onChange={e=>patch(n=>{n.stations.find(s=>s.id===station.id)!.labelRotation=Number(e.target.value)||0})}/></div></Field>
        <div className="field-grid"><Field label="偏移 X"><input aria-label="站名偏移 X" type="number" step="0.1" value={round(station.labelOffsetX)} onChange={e=>patch(n=>{n.stations.find(s=>s.id===station.id)!.labelOffsetX=Number(e.target.value)||0})}/></Field><Field label="偏移 Y"><input aria-label="站名偏移 Y" type="number" step="0.1" value={round(station.labelOffsetY)} onChange={e=>patch(n=>{n.stations.find(s=>s.id===station.id)!.labelOffsetY=Number(e.target.value)||0})}/></Field></div>
        <button onClick={()=>patch(n=>{const target=n.stations.find(s=>s.id===station.id)!,offset=labelOffsetFor(n.settings.defaultLabelDirection,n.settings.defaultLabelDistance);target.labelOffsetX=offset.x;target.labelOffsetY=offset.y;delete target.labelRotation})}>恢复默认站名布局</button>
      </section>      <Field label="最早运营（由线路关系决定）"><input readOnly value={project.stationLineRelations.filter(r => r.stationId === station.id && r.openedAt).map(r => r.openedAt!).sort()[0] ?? '未设置'} /></Field>
      <Field label="方向锚定线路"><select value={station.orientationAnchorLineId ?? ''} onChange={(e) => patch((n) => { n.stations.find((s) => s.id === station.id)!.orientationAnchorLineId = e.target.value || undefined })}><option value="">自动：最早线路</option>{project.lines.filter((l) => project.stationLineRelations.some((r) => r.stationId === station.id && r.lineId === l.id)).map((l) => <option key={l.id} value={l.id}>{l.name}</option>)}</select></Field>
      <div className="relation-list"><span className="eyebrow">线路服务时间</span>{project.stationLineRelations.filter((r) => r.stationId === station.id).map((relation) => <div key={relation.id} className="field-grid"><Field label={`${project.lines.find((l) => l.id === relation.lineId)?.name ?? relation.lineId}${phaseForRelation(project, relation.id) ? phaseForRelation(project, relation.id)?.overriddenStationRelationIds?.includes(relation.id) ? ' · 已单独覆盖' : ' · 阶段成员' : ''}`}><input type="date" value={relation.openedAt ?? ''} onChange={(e) => patch((n) => { markRelationDateOverride(n, relation.id); n.stationLineRelations.find((r) => r.id === relation.id)!.openedAt = e.target.value || null })} /></Field><Field label="停运"><input type="date" value={relation.closedAt ?? ''} onChange={(e) => patch((n) => { n.stationLineRelations.find((r) => r.id === relation.id)!.closedAt = e.target.value || null })} /></Field></div>)}</div>
      <label className="toggle-row">隐藏本站标签<input type="checkbox" checked={!!station.labelHidden} onChange={(e) => patch((n) => { n.stations.find((s) => s.id === station.id)!.labelHidden = e.target.checked })} /></label>
      <button className="danger" onClick={onDelete}>删除站点</button>
    </> }
  } else if (selection?.type === 'line') {
    const line = project.lines.find((item) => item.id === selection.id)
    if (line) content = <>
      <h3>线路</h3>
      <Field label="名称"><input value={line.name} onChange={(e) => patch((n) => { n.lines.find((l) => l.id === line.id)!.name = e.target.value })} /></Field>
      <Field label="线路颜色"><input type="color" value={line.color} onChange={(e) => patch((n) => { n.lines.find((l) => l.id === line.id)!.color = e.target.value })} /></Field>
      <Field label="开通日期"><input type="date" value={line.openedAt ?? ''} onChange={(e) => patch((n) => { n.lines.find((l) => l.id === line.id)!.openedAt = e.target.value || null })} /></Field>
      <Field label="停运日期"><input type="date" value={line.closedAt ?? ''} onChange={(e) => patch((n) => { n.lines.find((l) => l.id === line.id)!.closedAt = e.target.value || null })} /></Field>
      <OpeningPhaseEditor project={project} line={line} onChange={onChange} onPreview={onPhasePreview} onStartDrawing={onStartPhaseDrawing} />
      <label className="toggle-row">锁定线路<input type="checkbox" checked={line.locked} onChange={(e) => patch((n) => { n.lines.find((l) => l.id === line.id)!.locked = e.target.checked })} /></label>
      {line.stationSequence.length >= 3 && <button onClick={() => patch((n) => { const current = n.lines.find((l) => l.id === line.id)!; const from = current.stationSequence.at(-1)!; const to = current.stationSequence[0]; const exists = n.geometry.segments.some((s) => s.lineId === line.id && ((s.fromStationId === from && s.toStationId === to) || (s.fromStationId === to && s.toStationId === from))); if (!exists) n.geometry.segments.push({ id: uid('segment_loop'), lineId: line.id, fromStationId: from, toStationId: to, mode: 'straight', structureType: 'underground', waypoints: [], openedAt: line.openedAt }) })}>连接首尾形成环线</button>}
      <button className="danger" onClick={onDelete}>删除线路</button>
    </>
  } else if (selection?.type === 'segment') {
    const segment = project.geometry.segments.find((item) => item.id === selection.id)
    if (segment) content = <>
      <h3>区间</h3>
      <Field label="绘制模式"><select value={segment.mode} onChange={(e) => patch((n) => { n.geometry.segments.find((s) => s.id === segment.id)!.mode = e.target.value as SegmentMode })}><option value="straight">直线</option><option value="smooth">平滑</option><option value="corner">折角</option><option value="rounded">局部圆角</option></select></Field><Field label="区间起始结构"><select value={segment.structureType} onChange={(e) => patch((n) => { n.geometry.segments.find((s) => s.id === segment.id)!.structureType = e.target.value as StructureType })}><option value="underground">普通 / 地下</option><option value="elevated">高架</option><option value="ground">地面（预留）</option></select></Field>
      <Field label="开通日期"><input type="date" value={segment.openedAt ?? ''} onChange={(e) => patch((n) => { markSegmentDateOverride(n, segment.id); n.geometry.segments.find((s) => s.id === segment.id)!.openedAt = e.target.value || null })} /></Field><Field label="停运日期"><input type="date" value={segment.closedAt ?? ''} onChange={(e) => patch((n) => { n.geometry.segments.find((s) => s.id === segment.id)!.closedAt = e.target.value || null })} /></Field>
      {phaseForSegment(project, segment.id) && <p className="meta-note">开通阶段：{phaseForSegment(project, segment.id)?.name || '未命名阶段'}{phaseForSegment(project, segment.id)?.overriddenSegmentIds?.includes(segment.id) ? ' · 已单独覆盖' : ''}</p>}
      <p className="meta-note">{segment.waypoints.length} 个控制点 · 双击区间继续添加</p>
      <button onClick={() => patch((n) => { const s = n.geometry.segments.find((x) => x.id === segment.id)!; s.waypoints = []; s.mode = 'straight' })}>清空控制点并恢复直线</button>
      <button className="danger" onClick={onDelete}>删除区间</button>
    </>
  } else if (selection?.type === 'waypoint') {
    const waypoint = project.geometry.segments.find((s) => s.id === selection.segmentId)?.waypoints.find((w) => w.id === selection.id)
    if (waypoint) { const segment=project.geometry.segments.find((s)=>s.id===selection.segmentId)!; content = <><h3>控制点</h3><Field label="点类型"><select value={waypoint.type} onChange={(e) => patch((n) => { n.geometry.segments.find((s) => s.id === selection.segmentId)!.waypoints.find((w) => w.id === waypoint.id)!.type = e.target.value as 'smooth' | 'corner' })}><option value="smooth">平滑</option><option value="corner">折角</option></select></Field><Field label="从此处开始"><select value={getWaypointStructureAfter(segment,waypoint.id)??''} onChange={(e)=>onChange(setWaypointStructureAfter(project,segment.id,waypoint.id,(e.target.value||null) as StructureType|null))}><option value="">结构不改变</option><option value="underground">地下</option><option value="elevated">高架</option><option value="ground">地面（预留）</option></select></Field><p className="meta-note">线路形状与结构类型相互独立；移动控制点时，附着的结构切换点会同步移动。</p><button className="danger" onClick={onDelete}>删除控制点</button></> }
  } else if (selection?.type === 'structureNode') {
    const node=project.geometry.segments.find(segment=>segment.id===selection.segmentId)?.structureNodes?.find(item=>item.id===selection.id)
    if(node)content=<><h3>结构节点</h3><Field label="从此处开始"><select value={node.structureAfter} onChange={event=>onChange(updateStructureNode(project,selection.segmentId,node.id,event.target.value as StructureType))}><option value="underground">地下</option><option value="elevated">高架</option><option value="ground">地面（预留）</option></select></Field><p className="meta-note">只改变线路结构，不改变原有曲线。</p><button className="danger" onClick={onDelete}>删除结构节点</button></>
  } else if (selection?.type === 'mapElement') {
    const element = project.mapElements?.find(item => item.id === selection.id)
    if (element?.type === 'lineBadge') content = <><h3>线路标号</h3><Field label="线路"><select value={element.lineId} onChange={event=>patch(next=>{const target=next.mapElements?.find(item=>item.id===element.id);if(target?.type==='lineBadge')target.lineId=event.target.value})}>{project.lines.map(line=><option key={line.id} value={line.id}>{line.name}</option>)}</select></Field><Field label="大小"><input type="number" min="12" max="200" step="1" value={element.size} onChange={event=>patch(next=>{const target=next.mapElements?.find(item=>item.id===element.id);if(target?.type==='lineBadge')target.size=Math.max(12,Number(event.target.value)||12)})}/></Field><Field label="旋转"><input type="number" step="1" value={element.rotation} onChange={event=>patch(next=>{const target=next.mapElements?.find(item=>item.id===element.id);if(target)target.rotation=Number(event.target.value)||0})}/></Field><label className="toggle-row">显示<input type="checkbox" checked={element.visible} onChange={event=>patch(next=>{const target=next.mapElements?.find(item=>item.id===element.id);if(target)target.visible=event.target.checked})}/></label><p className="meta-note">颜色自动使用所选线路的标识色；可在画布上直接拖动。</p><button className="danger" onClick={onDelete}>删除线路标号</button></>
    else if (element?.type === 'text') content = <><h3>自由文本</h3><Field label="文字"><textarea rows={5} value={element.text} onChange={event=>patch(next=>{const target=next.mapElements?.find(item=>item.id===element.id);if(target?.type==='text')target.text=event.target.value})}/></Field><Field label="字号"><input type="number" min="6" max="240" step="1" value={element.fontSize} onChange={event=>patch(next=>{const target=next.mapElements?.find(item=>item.id===element.id);if(target?.type==='text')target.fontSize=Math.max(6,Number(event.target.value)||6)})}/></Field><Field label="字重"><select value={element.fontWeight} onChange={event=>patch(next=>{const target=next.mapElements?.find(item=>item.id===element.id);if(target?.type==='text')target.fontWeight=event.target.value==='bold'?'bold':'normal'})}><option value="normal">常规</option><option value="bold">粗体</option></select></Field><Field label="对齐"><select value={element.textAlign} onChange={event=>patch(next=>{const target=next.mapElements?.find(item=>item.id===element.id);if(target?.type==='text')target.textAlign=event.target.value as 'start'|'middle'|'end'})}><option value="start">左对齐</option><option value="middle">居中</option><option value="end">右对齐</option></select></Field><Field label="旋转"><input type="number" step="1" value={element.rotation} onChange={event=>patch(next=>{const target=next.mapElements?.find(item=>item.id===element.id);if(target)target.rotation=Number(event.target.value)||0})}/></Field><label className="toggle-row">显示<input type="checkbox" checked={element.visible} onChange={event=>patch(next=>{const target=next.mapElements?.find(item=>item.id===element.id);if(target)target.visible=event.target.checked})}/></label><p className="meta-note">支持换行；可在画布上直接拖动。</p><button className="danger" onClick={onDelete}>删除自由文本</button></>
  } else if (selection?.type === 'background' && project.background) {
    const bg = project.background
    content = <><h3>底图</h3><Field label="透明度"><input type="range" min="0" max="1" step="0.05" value={bg.opacity} onChange={(e) => patch((n) => { n.background!.opacity = Number(e.target.value) })} /></Field><div className="field-grid"><Field label="X"><input type="number" value={bg.x} onChange={(e) => patch((n) => { n.background!.x = Number(e.target.value) })} /></Field><Field label="Y"><input type="number" value={bg.y} onChange={(e) => patch((n) => { n.background!.y = Number(e.target.value) })} /></Field><Field label="宽度"><input type="number" value={bg.width} onChange={(e) => patch((n) => { n.background!.width = Number(e.target.value) })} /></Field><Field label="高度"><input type="number" value={bg.height} onChange={(e) => patch((n) => { n.background!.height = Number(e.target.value) })} /></Field></div><button className="danger" onClick={onDelete}>移除底图</button></>
  }
  return <aside className="right-panel panel"><div className="panel-heading"><div><h2>属性</h2><span className="panel-subtitle">当前选择</span></div></div><div className="inspector-body">{content}</div></aside>
}
