import type { ActualRouteProject, LabelDirection } from '../data/model'
import { LABEL_DIRECTIONS, resetVisualSettings } from '../data/style'
import { CHINESE_FONT_PRESETS, ColorControl, FontFamilyControl, FontWeightControl, FOREIGN_FONT_PRESETS } from './TypographyControls'

const StyleNumber=({label,value,min,max,step,onChange}:{label:string;value:number;min:number;max:number;step:number;onChange:(value:number)=>void})=><label className="style-range"><span>{label}</span><div><input aria-label={`${label}滑块`} type="range" min={min} max={max} step={step} value={Math.max(min,Math.min(max,value))} onChange={event=>onChange(Number(event.target.value))}/><input aria-label={label} className="style-number" type="number" inputMode="decimal" step={step} value={value} onChange={event=>{const next=Number(event.target.value);if(Number.isFinite(next))onChange(next)}}/></div></label>

export function StyleDrawer({project,onChange,onClose,embedded=false}:{project:ActualRouteProject;onChange:(project:ActualRouteProject)=>void;onClose:()=>void;embedded?:boolean}){
  const patch=(mutate:(next:ActualRouteProject)=>void)=>{const next=structuredClone(project);mutate(next);onChange(next)}
  const setNumber=(key:keyof ActualRouteProject['settings'],value:number)=>patch(next=>{(next.settings[key] as number)=value})
  const panel=<aside className={`style-drawer${embedded?' style-drawer-embedded':''}`} role={embedded?undefined:'dialog'} aria-modal={embedded?undefined:true} aria-label="全局样式">
    <header><div><h2>全局样式</h2><span className="panel-subtitle">修改后立即应用到整张线路图</span></div><button className="icon-button" aria-label="关闭全局样式" onClick={onClose}>×</button></header>
    <div className="style-drawer-body">
      <details open><summary>线路</summary><StyleNumber label="线路宽度" value={project.settings.lineWidth} min={6} max={40} step={.5} onChange={value=>setNumber('lineWidth',value)}/></details>
      <details open><summary>车站</summary><StyleNumber label="普通站点大小" value={project.settings.stationSize} min={3} max={30} step={.5} onChange={value=>setNumber('stationSize',value)}/><StyleNumber label="换乘站宽度" value={project.settings.transferMinorAxis} min={8} max={50} step={.25} onChange={value=>setNumber('transferMinorAxis',value)}/><StyleNumber label="换乘站两端留白" value={project.settings.transferEndPadding} min={0} max={20} step={.05} onChange={value=>setNumber('transferEndPadding',value)}/><StyleNumber label="换乘圆点间距" value={project.settings.transferDotGap} min={0} max={16} step={.05} onChange={value=>setNumber('transferDotGap',value)}/></details>
      <details open><summary>站名</summary><h4>中文站名</h4><FontFamilyControl label="中文站名字体" value={project.settings.stationLabelFontFamily} presets={CHINESE_FONT_PRESETS} onChange={value=>patch(next=>{next.settings.stationLabelFontFamily=value})}/><StyleNumber label="中文站名字号" value={project.settings.stationLabelSize} min={6} max={40} step={.5} onChange={value=>setNumber('stationLabelSize',value)}/><FontWeightControl label="中文站名字重" value={project.settings.stationLabelFontWeight} onChange={value=>setNumber('stationLabelFontWeight',value)}/><ColorControl label="中文站名颜色" value={project.settings.stationLabelColor} onChange={value=>patch(next=>{next.settings.stationLabelColor=value})}/><h4>外文站名</h4><FontFamilyControl label="外文站名字体" value={project.settings.stationForeignLabelFontFamily} presets={FOREIGN_FONT_PRESETS} onChange={value=>patch(next=>{next.settings.stationForeignLabelFontFamily=value})}/><StyleNumber label="外文站名字号" value={project.settings.stationForeignLabelSize} min={4} max={30} step={.25} onChange={value=>setNumber('stationForeignLabelSize',value)}/><FontWeightControl label="外文站名字重" value={project.settings.stationForeignLabelFontWeight} onChange={value=>setNumber('stationForeignLabelFontWeight',value)}/><ColorControl label="外文站名颜色" value={project.settings.stationForeignLabelColor} onChange={value=>patch(next=>{next.settings.stationForeignLabelColor=value})}/><StyleNumber label="中文 / 外文间距" value={project.settings.foreignLabelGap} min={0} max={16} step={.25} onChange={value=>setNumber('foreignLabelGap',value)}/><h4>站名布局</h4><StyleNumber label="默认站名距离" value={project.settings.defaultLabelDistance} min={0} max={80} step={.5} onChange={value=>setNumber('defaultLabelDistance',value)}/><label className="style-select"><span>默认站名方向</span><select aria-label="默认站名方向" value={project.settings.defaultLabelDirection} onChange={event=>patch(next=>{next.settings.defaultLabelDirection=event.target.value as LabelDirection})}>{LABEL_DIRECTIONS.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="style-select"><span>默认站名旋转</span><div><select aria-label="默认旋转预设" value={[0,45,-45,90,-90].includes(project.settings.defaultStationLabelRotation)?project.settings.defaultStationLabelRotation:'custom'} onChange={event=>{if(event.target.value!=='custom')setNumber('defaultStationLabelRotation',Number(event.target.value))}}><option value="0">0°</option><option value="45">45°</option><option value="-45">-45°</option><option value="90">90°</option><option value="-90">-90°</option><option value="custom">自定义</option></select><input aria-label="默认站名旋转角度" type="number" inputMode="decimal" step="1" value={project.settings.defaultStationLabelRotation} onChange={event=>setNumber('defaultStationLabelRotation',Number(event.target.value)||0)}/></div></label></details>
      <details open><summary>显示与比例</summary><label className="style-range"><span>距离比例</span><div><input aria-label="每公里地图单位" type="number" inputMode="decimal" min="0.001" step="1" value={project.settings.worldUnitsPerKm} onChange={event=>{const value=Number(event.target.value);if(value>0)setNumber('worldUnitsPerKm',value)}}/><output>单位 / km</output></div></label><label className="toggle-row">显示网格<input type="checkbox" checked={project.settings.gridVisible} onChange={event=>patch(next=>{next.settings.gridVisible=event.target.checked})}/></label><label className="toggle-row">显示全部站名<input type="checkbox" checked={project.settings.labelsVisible} onChange={event=>patch(next=>{next.settings.labelsVisible=event.target.checked})}/></label><label className="toggle-row">显示外文站名<input type="checkbox" checked={project.settings.showForeignStationNames} onChange={event=>patch(next=>{next.settings.showForeignStationNames=event.target.checked})}/></label>{project.background&&<><label className="toggle-row">显示底图<input type="checkbox" checked={project.background.visible} onChange={event=>patch(next=>{next.background!.visible=event.target.checked})}/></label><label className="toggle-row">锁定底图<input type="checkbox" checked={project.background.locked} onChange={event=>patch(next=>{next.background!.locked=event.target.checked})}/></label></>}</details>
      <button className="reset-style" onClick={()=>patch(next=>{next.settings=resetVisualSettings(next.settings)})}>恢复默认样式</button>
    </div>
  </aside>
  return embedded ? panel : <><button data-android-back-dismiss className="style-drawer-scrim" aria-label="关闭全局样式面板" onClick={onClose}/>{panel}</>
}
