import { BUILD_VERSION } from '../build'

export function Toolbar({ canUndo, canRedo, undo, redo, fitAll, zoomSelection, importProject, importTopology, exportProject, exportSvg, shareProject=()=>undefined, shareSvg=()=>undefined, importBackground, onNewLine, onAddLineBadge=()=>undefined, onAddText=()=>undefined, onStyle, drawing, onFinish, onPresentation, nativeFiles=false }: {
  canUndo: boolean; canRedo: boolean; undo: () => void; redo: () => void; fitAll: () => void; zoomSelection: () => void
  importProject: () => void; importTopology: () => void; exportProject: () => void; exportSvg: () => void; shareProject?: () => void; shareSvg?: () => void; importBackground: () => void; onNewLine: () => void; onAddLineBadge?: () => void; onAddText?: () => void; onStyle: () => void; drawing: boolean; onFinish: () => void; onPresentation: () => void; nativeFiles?: boolean
}) {
  return <header className="toolbar direct-toolbar">
    <div className="brand"><span className="brand-mark">AR</span><div><strong>实际走向绘制器</strong><small>线路驱动 · 直接编辑</small></div></div>
    <div className="tool-group creation-group"><button className="primary" onClick={drawing ? onFinish : onNewLine}>{drawing ? '完成绘制' : '＋ 新建线路'}</button><details className="toolbar-menu map-elements-menu"><summary>地图元素▾</summary><div className="toolbar-menu-popover"><button onClick={onAddLineBadge}>添加线路标号</button><button onClick={onAddText}>添加自由文本</button></div></details><button onClick={onStyle}>样式</button><button className="presentation-entry" onClick={onPresentation}>发展史</button></div>
    <div className="tool-group mobile-core"><button onClick={undo} disabled={!canUndo}>撤销</button><button onClick={redo} disabled={!canRedo}>重做</button></div>
    <details className="toolbar-menu mobile-files"><summary>更多▾</summary><div className="toolbar-menu-popover"><button onClick={onAddLineBadge}>添加线路标号</button><button onClick={onAddText}>添加自由文本</button><button onClick={importProject}>导入工程 / AARC</button><button onClick={importBackground}>导入底图</button><button onClick={exportProject}>{nativeFiles ? '保存 JSON 到手机' : '导出 JSON'}</button><button onClick={exportSvg}>{nativeFiles ? '保存 SVG 到手机' : '导出 SVG'}</button><button onClick={shareProject}>分享 JSON</button><button onClick={shareSvg}>分享 SVG</button></div></details>
    <div className="tool-group desktop-tools"><button onClick={fitAll}>适应全部</button><button onClick={zoomSelection}>缩放到选择</button></div>
    <div className="tool-group push-right desktop-tools"><button onClick={importBackground}>底图</button><details className="toolbar-menu"><summary>导入▾</summary><div className="toolbar-menu-popover"><button onClick={importTopology}>导入拓扑</button><button onClick={importProject}>导入工程 / AARC</button></div></details><details className="toolbar-menu"><summary>导出▾</summary><div className="toolbar-menu-popover"><button onClick={exportProject}>{nativeFiles ? '保存工程到手机' : '导出工程'}</button><button onClick={exportSvg}>{nativeFiles ? '保存矢量图到手机' : '导出矢量图'}</button><button onClick={shareProject}>分享工程</button><button onClick={shareSvg}>分享矢量图</button></div></details><details className="toolbar-menu about-menu"><summary>更多▾</summary><div className="toolbar-menu-popover about-popover"><strong>关于</strong><span>实际走向绘制器</span><small>版本 {BUILD_VERSION}</small></div></details></div>
  </header>
}
