import { fireEvent, render, screen } from '@testing-library/react'
import { useState } from 'react'
import { describe, expect, it, vi } from 'vitest'
import { demoProject } from '../data/demo'
import type { ActualRouteProject } from '../data/model'
import { ContextActions } from './ContextActions'
import { StyleDrawer } from './StyleDrawer'
import { Timeline } from './Timeline'
import { Toolbar } from './Toolbar'
import { ProjectSettingsPanel } from './ProjectSettingsPanel'

function StyleHarness(){const [project,setProject]=useState<ActualRouteProject>(structuredClone(demoProject));const [open,setOpen]=useState(false);return <><Toolbar canUndo={false} canRedo={false} undo={()=>{}} redo={()=>{}} fitAll={()=>{}} zoomSelection={()=>{}} importProject={()=>{}} importTopology={()=>{}} exportProject={()=>{}} exportSvg={()=>{}} importBackground={()=>{}} onNewLine={()=>{}} onStyle={()=>setOpen(true)} drawing={false} onFinish={()=>{}} onPresentation={()=>{}}/>{open&&<StyleDrawer project={project} onChange={setProject} onClose={()=>setOpen(false)}/>}<output data-testid="line-width">{project.settings.lineWidth}</output><output data-testid="existing-line-width">{project.lines[0].lineWidth ?? 'fallback'}</output></>}

describe('editor information architecture',()=>{
 it('shows the project name in the desktop brand and synchronizes it with settings',()=>{const seed=structuredClone(demoProject);seed.projectName='木阳';seed.name='木阳';function Harness(){const [project,setProject]=useState(seed);const setName=(name:string)=>setProject(current=>({...current,projectName:name,name}));return <><Toolbar canUndo={false} canRedo={false} undo={()=>{}} redo={()=>{}} fitAll={()=>{}} zoomSelection={()=>{}} importProject={()=>{}} importTopology={()=>{}} exportProject={()=>{}} exportSvg={()=>{}} importBackground={()=>{}} onNewLine={()=>{}} onStyle={()=>{}} drawing={false} onFinish={()=>{}} onPresentation={()=>{}} projectName={project.projectName} onProjectNameChange={setName}/><ProjectSettingsPanel project={project} onChange={setProject}/></>}render(<Harness/>);fireEvent.click(screen.getByRole('button',{name:'当前工程名称'}));const inline=document.querySelector('.brand-project-name-input') as HTMLInputElement;fireEvent.change(inline,{target:{value:'平岚'}});fireEvent.keyDown(inline,{key:'Enter'});expect(screen.getByRole('button',{name:'当前工程名称'})).toHaveTextContent('平岚');expect((document.querySelector('.project-settings-panel input') as HTMLInputElement).value).toBe('平岚');const settingsInput=document.querySelector('.project-settings-panel input') as HTMLInputElement;fireEvent.focus(settingsInput);fireEvent.change(settingsInput,{target:{value:'新西'}});fireEvent.blur(settingsInput);expect(screen.getByRole('button',{name:'当前工程名称'})).toHaveTextContent('新西')})
 it('cancels inline project-name editing with Escape without mutation',()=>{const onProjectNameChange=vi.fn();render(<Toolbar canUndo={false} canRedo={false} undo={()=>{}} redo={()=>{}} fitAll={()=>{}} zoomSelection={()=>{}} importProject={()=>{}} importTopology={()=>{}} exportProject={()=>{}} exportSvg={()=>{}} importBackground={()=>{}} onNewLine={()=>{}} onStyle={()=>{}} drawing={false} onFinish={()=>{}} onPresentation={()=>{}} projectName="木阳" onProjectNameChange={onProjectNameChange}/>);fireEvent.click(screen.getByRole('button',{name:'当前工程名称'}));const inline=document.querySelector('.brand-project-name-input') as HTMLInputElement;fireEvent.change(inline,{target:{value:'平岚'}});fireEvent.keyDown(inline,{key:'Escape'});expect(screen.getByRole('button',{name:'当前工程名称'})).toHaveTextContent('木阳');expect(onProjectNameChange).not.toHaveBeenCalled()})
 it('changes the global style without writing an object field',()=>{render(<StyleHarness/>);fireEvent.click(screen.getByText('样式'));expect(screen.getByRole('dialog',{name:'全局样式'})).toBeTruthy();fireEvent.change(screen.getByRole('spinbutton',{name:'线路宽度'}),{target:{value:'21'}});expect(screen.getByTestId('line-width')).toHaveTextContent('21');expect(screen.getByTestId('existing-line-width')).toHaveTextContent('fallback');fireEvent.click(screen.getByRole('button',{name:'关闭全局样式'}));expect(screen.queryByRole('dialog',{name:'全局样式'})).toBeNull()})
 it('keeps all global style groups and exact numeric controls in the drawer',()=>{const onChange=vi.fn();render(<StyleDrawer project={structuredClone(demoProject)} onChange={onChange} onClose={()=>{}}/>);expect(screen.getByText('线路')).toBeTruthy();expect(screen.getByText('车站')).toBeTruthy();expect(screen.getByText('站名')).toBeTruthy();fireEvent.change(screen.getByRole('spinbutton',{name:'中文站名字号'}),{target:{value:'18'}});expect(onChange.mock.calls.at(-1)?.[0].settings.stationLabelSize).toBe(18);expect(screen.queryByText('修复 Build 16 样式继承')).toBeNull()})
 it('edits global station typography without materializing station overrides',()=>{const project=structuredClone(demoProject),onChange=vi.fn();render(<StyleDrawer project={project} onChange={onChange} onClose={()=>{}}/>);fireEvent.change(screen.getByLabelText('中文站名字体'),{target:{value:'SimHei, sans-serif'}});let next=onChange.mock.calls.at(-1)![0];expect(next.settings.stationLabelFontFamily).toBe('SimHei, sans-serif');expect(next.stations.every((station:{styleOverrides?:unknown})=>station.styleOverrides===undefined)).toBe(true);fireEvent.change(screen.getByLabelText('外文站名字重'),{target:{value:'400'}});next=onChange.mock.calls.at(-1)![0];expect(next.settings.stationForeignLabelFontWeight).toBe(400)})
 it('does not commit an invalid typography color',()=>{const onChange=vi.fn();render(<StyleDrawer project={structuredClone(demoProject)} onChange={onChange} onClose={()=>{}}/>);fireEvent.change(screen.getByLabelText('中文站名颜色 HEX'),{target:{value:'not-a-color'}});expect(onChange).not.toHaveBeenCalled()})
 it('uses one shared solid down triangle for the four toolbar dropdowns',()=>{render(<Toolbar canUndo={false} canRedo={false} undo={()=>{}} redo={()=>{}} fitAll={()=>{}} zoomSelection={()=>{}} importProject={()=>{}} importTopology={()=>{}} exportProject={()=>{}} exportSvg={()=>{}} importBackground={()=>{}} onNewLine={()=>{}} onStyle={()=>{}} drawing={false} onFinish={()=>{}} onPresentation={()=>{}}/>);const arrows=screen.getAllByTestId('dropdown-arrow');expect(arrows).toHaveLength(4);expect(arrows.every(arrow=>arrow.tagName.toLowerCase()==='svg'&&arrow.querySelector('path')?.getAttribute('d')==='M1 1l4 4 4-4Z')).toBe(true);expect(screen.queryByText(/▾$/)).toBeNull();expect(screen.queryByText(/⌄$/)).toBeNull()})
 it('keeps line badges out of the map-elements menu and exposes free text there once',()=>{render(<Toolbar canUndo={false} canRedo={false} undo={()=>{}} redo={()=>{}} fitAll={()=>{}} zoomSelection={()=>{}} importProject={()=>{}} importTopology={()=>{}} exportProject={()=>{}} exportSvg={()=>{}} importBackground={()=>{}} onNewLine={()=>{}} onStyle={()=>{}} drawing={false} onFinish={()=>{}} onPresentation={()=>{}}/>);expect(screen.queryByText('添加线路标号')).toBeNull();expect(screen.getAllByText('添加自由文本')).toHaveLength(1);expect(screen.getAllByRole('button',{name:'更多'})).toHaveLength(1)})
 it('offers the built-in line legend from the map-elements menu',()=>{render(<Toolbar canUndo={false} canRedo={false} undo={()=>{}} redo={()=>{}} fitAll={()=>{}} zoomSelection={()=>{}} importProject={()=>{}} importTopology={()=>{}} exportProject={()=>{}} exportSvg={()=>{}} importBackground={()=>{}} onNewLine={()=>{}} onStyle={()=>{}} drawing={false} onFinish={()=>{}} onPresentation={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'地图元素'}));expect(screen.getByRole('menuitem',{name:'添加线路图例'})).toBeTruthy()})
 it('keeps toolbar dropdowns mutually exclusive and closes before opening About',()=>{render(<Toolbar canUndo={false} canRedo={false} undo={()=>{}} redo={()=>{}} fitAll={()=>{}} zoomSelection={()=>{}} importProject={()=>{}} importTopology={()=>{}} exportProject={()=>{}} exportSvg={()=>{}} importBackground={()=>{}} onNewLine={()=>{}} onStyle={()=>{}} drawing={false} onFinish={()=>{}} onPresentation={()=>{}}/>);const imports=screen.getByRole('button',{name:'导入'}),exports=screen.getByRole('button',{name:'导出'}),more=screen.getByRole('button',{name:'更多'});fireEvent.click(imports);expect(imports).toHaveAttribute('aria-expanded','true');fireEvent.click(exports);expect(imports).toHaveAttribute('aria-expanded','false');expect(exports).toHaveAttribute('aria-expanded','true');fireEvent.click(more);fireEvent.click(screen.getByRole('menuitem',{name:'关于'}));expect(screen.getByRole('dialog',{name:'关于'})).toBeTruthy();expect(more).toHaveAttribute('aria-expanded','false')})
 it('places import and export actions in their single menus without share actions',()=>{render(<Toolbar canUndo={false} canRedo={false} undo={()=>{}} redo={()=>{}} fitAll={()=>{}} zoomSelection={()=>{}} importProject={()=>{}} importTopology={()=>{}} exportProject={()=>{}} exportSvg={()=>{}} importBackground={()=>{}} onNewLine={()=>{}} onStyle={()=>{}} drawing={false} onFinish={()=>{}} onPresentation={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'导入'}));expect(screen.getByRole('menuitem',{name:'导入工程 / AARC'})).toBeTruthy();expect(screen.getByRole('menuitem',{name:'导入底图'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'导出'}));expect(screen.getByRole('menuitem',{name:'导出工程'})).toBeTruthy();expect(screen.getByRole('menuitem',{name:'导出矢量图'})).toBeTruthy();expect(screen.getByRole('menuitem',{name:'导出图片…'})).toBeTruthy();expect(screen.queryByText('分享工程')).toBeNull();expect(screen.queryByText('分享矢量图')).toBeNull()})
 it('renders the Style drawer as a non-modal panel',()=>{render(<StyleDrawer project={structuredClone(demoProject)} onChange={()=>{}} onClose={()=>{}}/>);const drawer=screen.getByRole('dialog',{name:'全局样式'});expect(drawer).not.toHaveAttribute('aria-modal');expect(document.querySelector('.style-drawer-scrim')).toBeNull()})
 it('renders a compact Segment action bar with the shared structure arrow',()=>{render(<ContextActions project={demoProject} selection={{type:'segment',id:'a-1'}} onExtend={()=>{}} onInsertStation={()=>{}} onAddWaypoint={()=>{}} onStraighten={()=>{}} onStructureChange={()=>{}} onSetStructureAtPoint={()=>{}} onDelete={()=>{}}/>);const bar=screen.getByRole('region',{name:'区间快捷操作'});expect(bar).toHaveClass('context-action-bar');expect(screen.getByText('＋站点')).toBeTruthy();expect(screen.getByText('＋路径点')).toBeTruthy();expect(screen.getByText('结构')).toBeTruthy();expect(bar.querySelector('[data-testid="dropdown-arrow"]')).toBeTruthy();expect(screen.queryByText('结构⌄')).toBeNull();expect(screen.getByLabelText('更多区间操作')).toBeTruthy()})
 it('collapses Timeline by default when the project has no meaningful dates',()=>{const project=structuredClone(demoProject);[...project.lines,...project.stations,...project.stationLineRelations,...project.geometry.segments].forEach(item=>{item.openedAt=null;item.closedAt=null});render(<Timeline project={project} onChange={()=>{}}/>);expect(screen.getByText(/无时间数据/)).toBeTruthy();expect(screen.getByText('展开')).toBeTruthy();expect(screen.queryByLabelText('时间轴')).toBeNull()})
 it('keeps Timeline expanded when dates exist',()=>{render(<Timeline project={structuredClone(demoProject)} onChange={()=>{}}/>);expect(screen.getByLabelText('时间轴')).toBeTruthy()})
})
