import { render } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import { demoProject } from '../data/demo'
import { exportSvg } from '../import-export/svgExport'
import { StationMarker } from './StationMarker'
import { getDefaultTransferMetrics, getStationStyle, TRANSFER_DOT_DIAMETER_RATIO } from './stationStyles'
import { getBuiltInStationStyle } from '../data/presetRegistry'
import { resolveSideMarkerPlacement } from '../geometry/sideMarker'
const transferProps=()=>({size:demoProject.settings.stationSize,minorAxis:demoProject.settings.transferMinorAxis,dotGap:demoProject.settings.transferDotGap,endPadding:demoProject.settings.transferEndPadding,rotation:0})
describe('station styles',()=>{
 it('renders a stationDiameter of 14 as an SVG radius of 7 independently from lineWidth',()=>{const project=structuredClone(demoProject);project.settings.lineWidth=22.035;project.settings.stationSize=14;const {getByTestId}=render(<svg><StationMarker project={project} station={project.stations[0]} time="2025-01-01" selected={false} onPointerDown={()=>{}} onLabelPointerDown={()=>{}}/></svg>);expect(getByTestId('station-s1')).toHaveAttribute('r','7')})
 it('uses actual world-unit transfer dimensions and the new major axis',()=>{const metrics=getDefaultTransferMetrics(11,2,2.25,5.15,19.5);expect(metrics).toMatchObject({dotDiameter:8.8,gap:2.25,horizontalPadding:5.15,height:19.5});expect(metrics.width).toBeCloseTo(30.15)})
 it('uses one formula for 2/3/4 lines and stationSize times 0.8 for every dot',()=>{expect(TRANSFER_DOT_DIAMETER_RATIO).toBe(.8);for(const count of [2,3,4]){const metrics=getDefaultTransferMetrics(14,count,2.25,5.15,19.5);expect(metrics.width).toBeCloseTo(count*14*.8+(count-1)*2.25+10.3);expect(metrics.height).toBe(19.5);expect(metrics.dotDiameter).toBeCloseTo(11.2)}})
 it('adds an outline only to the transfer container and preserves it in SVG export',()=>{const station=demoProject.stations.find(item=>item.id==='s2')!,{container}=render(<svg><StationMarker project={demoProject} station={station} time="2025-01-01" selected={false} onPointerDown={()=>{}} onLabelPointerDown={()=>{}}/></svg>),transfer=container.querySelector('[data-testid="transfer-s2"]')!,frame=transfer.querySelector('rect')!;expect(frame).toHaveAttribute('fill','white');expect(frame).toHaveAttribute('stroke','#3f454a');expect(frame).toHaveAttribute('stroke-width','1.75');expect([...transfer.querySelectorAll('circle')].every(dot=>!dot.hasAttribute('stroke'))).toBe(true);expect(exportSvg(container.querySelector('svg')!,true)).toContain('stroke="#3f454a"')})
 it('uses the same actual dimensions during presentation morph',()=>{const station=demoProject.stations.find(item=>item.id==='s2')!,style=getStationStyle('default'),lines=demoProject.lines.slice(0,2),{container}=render(<svg>{style.renderPresentation({station,previousLines:[lines[0]],lines,...transferProps(),morphProgress:1,opacity:1,scale:1})}</svg>),frame=container.querySelector('rect')!,dots=[...container.querySelectorAll('circle')];expect(Number(frame.getAttribute('width'))).toBeCloseTo(30.15);expect(frame).toHaveAttribute('height','19.5');expect(frame).toHaveAttribute('stroke','#3f454a');expect(dots.slice(-2).every(dot=>dot.getAttribute('r')==='4.4')).toBe(true)})
 it('keeps the complete two-line container visible at the first frame of a three-line morph',()=>{const station=demoProject.stations.find(item=>item.id==='s2')!,style=getStationStyle('default'),lines=demoProject.lines.slice(0,3),{container}=render(<svg>{style.renderPresentation({station,previousLines:lines.slice(0,2),lines,...transferProps(),morphProgress:0,opacity:1,scale:1})}</svg>),frame=container.querySelector('rect')!,dots=[...container.querySelectorAll('circle')];expect(Number(frame.getAttribute('width'))).toBeCloseTo(30.15);expect(dots[0]).toHaveAttribute('opacity','1');expect(dots[1]).toHaveAttribute('opacity','1');expect(dots[2]).toHaveAttribute('opacity','0')})
 it('falls back to default style for future ids',()=>expect(getStationStyle('custom_x').id).toBe('default'))
 it('renders Shanghai as a service-colour outward marker attached to the local line edge',()=>{const project=structuredClone(demoProject);project.settings.lineWidth=20;project.stations[0].stationStyleId='station.shanghai.basic';const {container}=render(<svg><StationMarker project={project} station={project.stations[0]} time="2025-01-01" selected={false} onPointerDown={()=>{}} onLabelPointerDown={()=>{}}/></svg>);const artwork=container.querySelector('.station-artwork')!,rect=artwork.querySelector('rect')!,placement=resolveSideMarkerPlacement(project,'s1','line-a',{placementMode:'outward',depthRatio:1.35,thicknessRatio:.6});expect(artwork).toHaveAttribute('data-side-marker-mode','outward');expect(artwork).toHaveAttribute('data-side-marker-line-width','20');expect(Number(rect.getAttribute('width'))).toBeCloseTo(placement.thickness);expect(Number(rect.getAttribute('height'))).toBeCloseTo(placement.depth);expect(rect).toHaveAttribute('fill','#e54b3f');expect(rect).toHaveAttribute('stroke','none');expect(getBuiltInStationStyle('station.shanghai.basic')?.sidePlacementMode).toBe('outward')})
 it('renders MetroMan as a white, borderless inward marker that leaves the line visible',()=>{const project=structuredClone(demoProject);project.settings.lineWidth=20;project.stations[0].stationStyleId='station.metroman.basic';const {container}=render(<svg><StationMarker project={project} station={project.stations[0]} time="2025-01-01" selected={false} onPointerDown={()=>{}} onLabelPointerDown={()=>{}}/></svg>);const artwork=container.querySelector('.station-artwork')!,rect=artwork.querySelector('rect')!,placement=resolveSideMarkerPlacement(project,'s1','line-a',{placementMode:'inward',depthRatio:.5,thicknessRatio:.36});expect(artwork).toHaveAttribute('data-side-marker-mode','inward');expect(rect).toHaveAttribute('fill','white');expect(rect).toHaveAttribute('stroke','none');expect(placement.depth).toBeCloseTo(10);expect(placement.depth).toBeLessThan(placement.lineWidth);expect(Number(rect.getAttribute('height'))).toBeCloseTo(placement.depth);expect(getBuiltInStationStyle('station.metroman.basic')?.sidePlacementMode).toBe('inward')})
})
